//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityJs.EF6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentType
    {
        public IncidentType()
        {
            this.Incidents = new HashSet<Incident>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string BackgroundColor { get; set; }
        public int Importance { get; set; }
    
        public virtual ICollection<Incident> Incidents { get; set; }
    }
}
