//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityJs.EF6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderItmes = new HashSet<OrderItme>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Price { get; set; }
        public Nullable<int> PhotoID { get; set; }
        public Nullable<int> BigPhotoID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual File Photo { get; set; }
        public virtual File BigPhoto { get; set; }
        public virtual ICollection<OrderItme> OrderItmes { get; set; }
    }
}
