//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityJs.EF6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Incidents = new HashSet<Incident>();
            this.UserSettings = new HashSet<UserSetting>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public int RoleID { get; set; }
    
        public virtual ICollection<Incident> Incidents { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<UserSetting> UserSettings { get; set; }
    }
}
